version: '3.8'

services:
  helios-ai:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: helios-ai-app
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    volumes:
      # 로그 파일 저장용 (선택사항)
      - ./logs:/app/logs
      # 모델 파일 저장용 (선택사항)
      - ./models:/app/models
    networks:
      - helios-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # nginx 리버스 프록시 (선택사항)
  nginx:
    image: nginx:alpine
    container_name: helios-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      # SSL 인증서 (필요시)
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - helios-ai
    networks:
      - helios-network
    restart: unless-stopped

networks:
  helios-network:
    driver: bridge

volumes:
  app-logs:
  app-models:
